version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: czytacz
      POSTGRES_DB: czytacz
      POSTGRES_PASSWORD: czytacz
  mq:
    image: rabbitmq:latest
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=czytacz
      - RABBITMQ_DEFAULT_PASS=czytacz
  api:
    build: 
      context: .
      labels: 
        - modzero/czytacz
    command: scripts/start-api.sh
    depends_on:
      - db
      - mq
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=czytacz
      - POSTGRES_PASSWORD=czytacz
      - POSTGRES_DB=czytacz
      - POSTGRES_SERVER=db
      - RABBITMQ_URI=amqp://czytacz:czytacz@mq//
  worker:
    build: 
      context: .
      labels: 
        - modzero/czytacz
    command: scripts/start-worker.sh
    depends_on:
      - db
      - mq
    environment:
      - POSTGRES_USER=czytacz
      - POSTGRES_PASSWORD=czytacz
      - POSTGRES_DB=czytacz
      - POSTGRES_SERVER=db
      - RABBITMQ_URI=amqp://czytacz:czytacz@mq//

volumes:
  postgres-data:
  rabbitmq-data: