"""Cascade deletes

Revision ID: 023bd05754af
Revises: ba5acdf00097
Create Date: 2023-11-29 03:41:37.533515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023bd05754af'
down_revision: Union[str, None] = 'ba5acdf00097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_feed_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'feed', ['feed_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_feed_id_fkey', 'item', 'feed', ['feed_id'], ['id'])
    # ### end Alembic commands ###
