"""Add read status.

Revision ID: 44191d13db28
Revises: 4f1d5195882c
Create Date: 2023-11-29 08:56:45.525001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44191d13db28'
down_revision: Union[str, None] = '4f1d5195882c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('read', sa.Boolean(), nullable=False, server_default="False"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'read')
    # ### end Alembic commands ###
