"""Add a 'last updated' field

Revision ID: 7846e4e5fb8e
Revises: 023bd05754af
Create Date: 2023-11-29 03:48:58.260039

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7846e4e5fb8e"
down_revision: Union[str, None] = "023bd05754af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("item", sa.Column("updated", sa.DateTime(), nullable=True))
    op.execute(
        """
    UPDATE item AS i 
    SET updated = COALESCE(i.published, CAST(f.last_modified AS TIMESTAMP))
    FROM feed AS f
    WHERE f.id = i.feed_id
    """
    )
    op.alter_column("item", "updated", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "updated")
    # ### end Alembic commands ###
