"""Feed items

Revision ID: ba5acdf00097
Revises: 0853c44fb4ff
Create Date: 2023-11-28 18:59:19.675897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba5acdf00097'
down_revision: Union[str, None] = '0853c44fb4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.add_column('feed', sa.Column('actual_source', sa.String(), nullable=True))
    op.add_column('feed', sa.Column('etag', sa.String(), nullable=True))
    op.add_column('feed', sa.Column('last_modified', sa.String(), nullable=True))
    op.alter_column('feed', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('feed', 'last_modified')
    op.drop_column('feed', 'etag')
    op.drop_column('feed', 'actual_source')
    op.drop_table('item')
    # ### end Alembic commands ###
